# Generated by Django 3.2.12 on 2022-10-15 11:31

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workside', '0010_alter_worksite_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Inspection Report Name')),
                ('worksite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workside.worksite')),
            ],
            options={
                'verbose_name': 'Inspection Report',
                'verbose_name_plural': 'Inspection Reports',
            },
        ),
        migrations.CreateModel(
            name='InspectionReportMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=reports.models.inspection_report_media, verbose_name='Task attachments')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.inspectionreport')),
            ],
            options={
                'verbose_name': 'Inspection Report Media',
                'verbose_name_plural': 'Inspection Report Medias',
            },
        ),
        migrations.CreateModel(
            name='InspectionArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Area Name')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.inspectionreport')),
                ('tasks', models.ManyToManyField(to='workside.Task')),
            ],
            options={
                'verbose_name': 'Inspection Report Area',
                'verbose_name_plural': 'Inspection Report Areas',
            },
        ),
    ]
