# Generated by Django 3.2.12 on 2022-10-15 15:25

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0010_alter_worksite_notes'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreportmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=reports.models.inspection_report_media, verbose_name='Report attachments'),
        ),
        migrations.CreateModel(
            name='TaskFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.CharField(blank=True, choices=[('SATISFACTORY', 'SATISFACTORY'), ('NEEDS_ATTENTION', 'NEEDS_ATTENTION'), ('UNSATISFACTORY', 'UNSATISFACTORY')], max_length=200, null=True, verbose_name='Task Feedback')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.inspectionreport')),
                ('tasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workside.task')),
            ],
            options={
                'verbose_name': 'Task Feedback',
                'verbose_name_plural': 'Tasks Feedbacks',
            },
        ),
    ]
