# Generated by Django 3.2 on 2022-08-13 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import subscriptions.enums
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('period', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY')], default=subscriptions.enums.SubscriptionPeriod['YEARLY'], max_length=200)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscriptions Plans',
            },
        ),
        migrations.CreateModel(
            name='UsersSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('expiry', models.DateTimeField()),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Users Subscription',
                'verbose_name_plural': 'Users Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', tinymce.models.HTMLField()),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription Detail',
                'verbose_name_plural': 'Subscription Details',
            },
        ),
    ]
