# Generated by Django 2.2.28 on 2022-08-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workside',
            old_name='phone_number',
            new_name='contact_phone_number',
        ),
    ]
