# Generated by Django 3.2 on 2022-08-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0002_auto_20220807_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskattachments',
            options={'verbose_name': 'Task Attachment', 'verbose_name_plural': 'Task Attachments'},
        ),
        migrations.AddField(
            model_name='taskattachments',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workside.task'),
        ),
        migrations.AddField(
            model_name='workside',
            name='show_dtails',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Task Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Task Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Task Notes'),
        ),
        migrations.AlterField(
            model_name='task',
            name='workside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workside.workside'),
        ),
    ]
