# Generated by Django 3.2 on 2022-08-17 12:03

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import workside.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_employee_profile_image'),
        ('workside', '0003_auto_20220816_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='WorkSide Name')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='WorkSide Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='WorkSide Description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='WorkSide Description')),
                ('monthly_rates', models.CharField(blank=True, max_length=10, null=True, verbose_name='WorkSide Monthly Rates')),
                ('clear_frequency_by_day', models.CharField(blank=True, choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=10, null=True, verbose_name='WorkSide Monthly Rates')),
                ('desired_time', models.TimeField(blank=True, null=True)),
                ('number_of_workers_needed', models.IntegerField(blank=True, null=True, verbose_name='WorkSide Num Of Workers Needed')),
                ('supplies_needed', models.IntegerField(blank=True, null=True, verbose_name='WorkSide Supplier Needed')),
                ('contact_person_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contact Person Name')),
                ('contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('logo', models.FileField(blank=True, null=True, upload_to=workside.models.business_directory_path, verbose_name='Worksidet Logo')),
                ('instruction_video', models.FileField(blank=True, null=True, upload_to=workside.models.business_directory_path, verbose_name='Profile Picture')),
                ('show_dtails', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
            options={
                'verbose_name': 'Worksite',
                'verbose_name_plural': 'Worksites',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='workside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workside.worksite'),
        ),
        migrations.DeleteModel(
            name='WorkSide',
        ),
    ]
