# Generated by Django 3.2 on 2022-08-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0004_auto_20220817_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='workside',
            new_name='worksite',
        ),
    ]
