# Generated by Django 2.2.28 on 2022-08-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0005_rename_workside_task_worksite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='criticality',
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency_of_task',
            field=models.CharField(blank=True, choices=[('EVERY_TIME', 'EVERY_TIME'), ('WEEKLY', 'WEEKLY'), ('SEMI_WEEKLY', 'SEMI_WEEKLY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('SEMI_ANNUALLY', 'SEMI_ANNUALLY'), ('CUSTOM', 'CUSTOM')], max_length=10, null=True, verbose_name='Frequency Of Task'),
        ),
    ]
