# Generated by Django 2.2.28 on 2022-08-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0006_auto_20220822_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='criticality',
            field=models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=200, null=True, verbose_name='Task Critically'),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency_of_task',
            field=models.CharField(blank=True, choices=[('EVERY_TIME', 'EVERY_TIME'), ('WEEKLY', 'WEEKLY'), ('SEMI_WEEKLY', 'SEMI_WEEKLY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('SEMI_ANNUALLY', 'SEMI_ANNUALLY'), ('CUSTOM', 'CUSTOM')], max_length=200, null=True, verbose_name='Frequency Of Task'),
        ),
    ]
