# Generated by Django 2.2.28 on 2022-08-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0008_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='publishing_reminder',
            field=models.CharField(blank=True, choices=[('ONE_DAY', 'ONE_DAY'), ('TWO_DAYS', 'TWO_DAYS'), ('ONE_WEEK', 'ONE_WEEK'), ('TWO_WEEKS', 'TWO_WEEKS'), ('ONE_MONTH', 'ONE_MONTH')], max_length=200, null=True, verbose_name='Reminder for publishing draft event'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='employees',
            field=models.ManyToManyField(to='business.Employee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='selected_tasks',
            field=models.ManyToManyField(to='workside.Task'),
        ),
    ]
