# Generated by Django 3.2.12 on 2022-10-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0009_auto_20220823_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksite',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='WorkSide Notes'),
        ),
    ]
