# Generated by Django 3.2.12 on 2022-10-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0010_alter_worksite_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksite',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='worksite',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
