# Generated by Django 3.2.12 on 2022-11-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0011_auto_20221028_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
