# Generated by Django 3.2.12 on 2022-11-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0013_alter_worksite_clear_frequency_by_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY')], max_length=200, null=True, verbose_name='Frequency Of Event'),
        ),
    ]
