# Generated by Django 3.2.12 on 2023-01-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0014_alter_event_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
