# Generated by Django 3.2.12 on 2023-01-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0015_event_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='frequency_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
