# Generated by Django 3.2.12 on 2023-01-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0016_event_frequency_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksite',
            name='supplies_needed',
            field=models.CharField(blank=True, max_length=20000, null=True, verbose_name='WorkSide Supplier Needed'),
        ),
    ]
