# Generated by Django 3.2.12 on 2023-01-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0019_alter_event_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksite',
            name='upload_instruction_video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
