# Generated by Django 2.2.28 on 2022-08-07 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20220805_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaddress',
            name='state',
        ),
        migrations.AlterField(
            model_name='businessaddress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.City'),
        ),
        migrations.AlterField(
            model_name='businessaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Country'),
        ),
    ]
