# Generated by Django 2.2.28 on 2022-08-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_emergencycontact_phone'),
        ('business', '0006_auto_20220807_0809'),
    ]

    operations = [
    ]
