# Generated by Django 3.2 on 2022-08-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20220812_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaddress',
            name='country',
        ),
        migrations.AddField(
            model_name='businessaddress',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.region'),
        ),
    ]
