# Generated by Django 3.2 on 2022-08-15 16:45

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20220815_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=business.models.employee_directory_path, verbose_name='Profile Picture'),
        ),
    ]
