# Generated by Django 3.2.12 on 2022-09-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_auto_20220901_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('CLOCK_IN', 'CLOCK_IN'), ('CLOCK_OUT', 'CLOCK_OUT')], max_length=200, null=True, verbose_name='Attendance Status'),
        ),
    ]
