# Generated by Django 3.2.12 on 2022-09-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=200),
        ),
    ]
