# Generated by Django 3.2.12 on 2022-09-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_auto_20220913_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='earnings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=200),
        ),
        migrations.AddField(
            model_name='attendance',
            name='hourly_rate',
            field=models.IntegerField(default=0),
        ),
    ]
