# Generated by Django 3.2.12 on 2022-10-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_auto_20220930_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='feedback',
            field=models.CharField(blank=True, choices=[('CONFIDENT', 'CONFIDENT'), ('HAPPY', 'HAPPY'), ('NEUTRAL', 'NEUTRAL'), ('WORRIED', 'WORRIED'), ('RUSHED', 'RUSHED'), ('UPSET', 'UPSET')], max_length=200, null=True, verbose_name='Attendance Feedback'),
        ),
    ]
