# Generated by Django 3.2.12 on 2022-10-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_alter_attendance_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Employee Location'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
