# Generated by Django 3.2.12 on 2022-11-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0010_alter_customer_balance'),
        ('business', '0018_auto_20221028_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text="The Business's Stripe Subscription object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription'),
        ),
    ]
