# Generated by Django 3.2.12 on 2022-11-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_feedback_feedbackmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_feedback',
            field=models.CharField(blank=True, choices=[('CONFIDENT', 'CONFIDENT'), ('HAPPY', 'HAPPY'), ('NEUTRAL', 'NEUTRAL'), ('WORRIED', 'WORRIED'), ('RUSHED', 'RUSHED'), ('UPSET', 'UPSET')], max_length=200, null=True, verbose_name='Attendance Feedback'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='feedback',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
