# Generated by Django 3.2.12 on 2023-01-07 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workside', '0018_event_parent'),
        ('business', '0022_auto_20221201_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workside.event'),
        ),
    ]
