# Generated by Django 3.2.12 on 2023-01-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_alter_attendance_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='worksite_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
