# Generated by Django 3.2.12 on 2023-01-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_attendance_worksite_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.region'),
        ),
    ]
