# Generated by Django 3.2.12 on 2023-01-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_employee_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
