# Generated by Django 3.2.12 on 2023-02-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_alter_employee_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_shift_completed',
            field=models.BooleanField(default=False),
        ),
    ]
