# Generated by Django 3.2.12 on 2023-10-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_auto_20230217_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hourly_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
