# Generated by Django 3.2.12 on 2023-10-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_auto_20231026_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
