# Generated by Django 3.2 on 2022-08-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_otp',
            name='is_expire',
            field=models.BooleanField(default=False),
        ),
    ]
