# Generated by Django 3.2.12 on 2022-11-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220926_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
    ]
